language: python
os: linux

jobs:
  include:
    # chrome
    - env:
      - SELENIUM_WEBDRIVER=default
      - ENABLE_GEOCACHE_TEST=1
      addons:
        chrome: stable
      before_script:
        - export CHROMEDRIVER_VERSION=`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        - wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        - mkdir chromedriver
        - unzip chromedriver_linux64.zip -d chromedriver
        - chmod +x chromedriver/chromedriver
        - export PATH=$PATH:$PWD/chromedriver

    # firefox
    - env:
        - SELENIUM_WEBDRIVER=firefox
        - ENABLE_GEOCACHE_TEST=1
      addons:
        firefox: latest
      before_script:
        - export GECKODRIVER_VERSION=`curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4`
        - wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
    
    # docker + smoketest
    - services:
      - docker

      before_install: []
      
      install:
        - docker pull python:3.8-alpine
      
      script:
        - docker build -t jacobsalumni/membermanagement .
        - docker run -d --name=smoke -e DJANGO_SECRET_KEY=smoke -p 8080:80 jacobsalumni/membermanagement
        - sleep 10
        - curl http://localhost:8080/healthcheck/
        - curl -L http://localhost:8080/healthcheck/static
      
      after_script:
        - docker stop smoke
    

python: "3.8"

# install the right version of node
# because we can't use multiple languages at once
before_install:
  - nvm install 12
  - nvm use 12

install:
  - yarn
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - yarn build
  - pytest
